### Setup

In [49]:
import torch

### Set seed

In [30]:
torch.manual_seed(0)
torch.cuda.manual_seed(0)

### Exercise 1

In [27]:
X = torch.rand((7, 7))

### Exercise 2

In [28]:
y = torch.rand((1, 7))

### Exercise 3

In [29]:
X_y  = torch.matmul(X, torch.transpose(y, 0, 1))

### Exercise 5

In [40]:
device = "cuda" if torch.cuda.is_available else "cpu"
x = torch.rand(2, 7)
y = torch.rand(2, 7)
try:
    x.to(device)
    y.to(device)
except AssertionError as e:
    device = "cpu"
    x.to(device)
    y.to(device)
    assert x.device.type == 'cpu'
    assert y.device.type == 'cpu'

### Exercise 6

In [42]:
x_y = torch.matmul(x, torch.transpose(y, 0, 1))

### Exercise 7

In [43]:
max_x_y, min_x_y = torch.max(x_y), torch.min(x_y)

### Exercise 8

In [47]:
idxmax_x_y, idx_min_x_y = torch.argmax(x_y), torch.argmin(x_y)
idxmax_x_y, idx_min_x_y

(tensor(0), tensor(2))

### Exercise 9

In [60]:
torch.manual_seed(7)
torch.cuda.manual_seed(7)

### Exercise 10

In [68]:
rand_complex = torch.rand((1, 1, 1, 10))
squeezed_rand_complex = torch.squeeze(rand_complex)

tensor([[[[0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196, 0.2147, 0.2816,
           0.6679, 0.7878]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196, 0.2147, 0.2816, 0.6679,
        0.7878]) torch.Size([10])


In [69]:
print(rand_complex, rand_complex.shape)
print(squeezed_rand_complex, squeezed_rand_complex.shape)

tensor([[[[0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196, 0.2147, 0.2816,
           0.6679, 0.7878]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196, 0.2147, 0.2816, 0.6679,
        0.7878]) torch.Size([10])
